### ISSUE TITLE
{TODO}

### ISSUE THREAD

**Issue by jaredstone1982** [jaredstone1982/CraftingCalcARK#7]
# Major Changes
- [ ] Create base DataSource object, extend to more defined objects (CraftingQueueDataSource)
- [ ] Create base ListAdapter object, extend to more defined objects (DisplayCaseListAdapter)
- [ ] Create Resource table in database, instead of using a static SparseArray

## Minor Changes
- [ ] Refactor all uses of Resources from within ListAdapter to Composition, can be confusing atm.
- [ ] Convert all SparseArray<Object> to HashMap<Long, Object>
- [ ] Add DEBUG menu commands for ease of resetting or displaying data

## Ideas
- [ ] Take 'quantity' out of Engram objects themselves and into the objects that encapsulate them. (Examples: DisplayCase, CraftingQueue, Showcase)

**Comment by jaredstone1982** [comment]
- [ ] Documentation!

**Comment by jaredstone1982** [comment]
[ ] Engram Details: Ability to add attachments to firearms

**Comment by jaredstone1982** [comment]
- [ ] Crafting timers
